baseURL = "https://npeeech.github.io/blog/"
languageCode = "ja-jp"
title = "いつか黒歴史"
theme = "nLegacy-theme"
hasCJKLanguage = true
publishDir = "docs"
canonifyurls = true
googleAnalytics = "G-B091BVYLCR"
staticDir = ['static']

[params]
    AuthorName = "nPeeech"
    IframeAccessCounterUrl = "https://script.google.com/macros/s/AKfycbyr8Uzn2HXNrW9NRADOZpXeYSdVm1Dn0Il5mIrl2_gSqGY8a9IOjwEup11024j2I7kY-A/exec"
[taxonomies]
    tag = "tags"
    archive = "archives"
