baseURL = "http://example.org/"
languageCode = "ja-jp"
title = "いつか黒歴史"
theme = "nLegacy-theme"
hasCJKLanguage = true
publishDir = "docs"

[params]
    AuthorName = "nPeeech"

[taxonomies]
    tag = "tags"
    archive = "archives"
